# Generated by Django 4.2.3 on 2023-07-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
