# Generated by Django 4.2.3 on 2023-08-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_mensalidade_status'),
        ('alunos', '0003_alter_aluno_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='mensalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.mensalidade'),
        ),
    ]
