# Generated by Django 4.2.3 on 2023-08-10 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_mensalidade_status'),
        ('alunos', '0004_alter_aluno_mensalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='mensalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financeiro.mensalidade'),
        ),
    ]
