# Generated by Django 4.2.3 on 2023-07-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')]),
        ),
    ]
