# Generated by Django 4.2.3 on 2023-07-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
