# Generated by Django 4.2.3 on 2023-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
