# Generated by Django 4.2.3 on 2023-07-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino_Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treino_dia', models.CharField(choices=[('SEG', 'SEGUNDA'), ('TER', 'TERÇA'), ('QUA', 'QUARTA'), ('QUI', 'QUINTA'), ('SEX', 'SEXTA'), ('SAB', 'SÁBADO'), ('DOM', 'DOMINGO')], max_length=3)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alunos.aluno')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treinos.treino')),
            ],
        ),
    ]
