# Generated by Django 4.2.3 on 2023-07-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0002_treino_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
