# Generated by Django 4.2.3 on 2023-07-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0004_alter_treino_aluno_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino_aluno',
            name='treino_qtd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treino_aluno',
            name='treino_series',
            field=models.IntegerField(default=0),
        ),
    ]
