# Generated by Django 4.2.3 on 2023-07-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0005_treino_aluno_treino_qtd_treino_aluno_treino_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True),
        ),
        migrations.AlterField(
            model_name='treino_aluno',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True),
        ),
    ]
